[general]
import = ["thorns.toml"]

[font]
size = 12.0

[font.bold_italic]
family = "Sarasa Term J"
style = "Bold"

[font.italic]
family = "Sarasa Term J"
style = "Regular"

[font.normal]
family = "Sarasa Term J"

[window]
opacity = 0.90
padding = { x = 4, y = 4 }

[cursor.style]
blinking = "On"

[terminal]
shell = "zsh"
