[general]
import = ["thorns.toml"]

[font]
size = 12.0

[font.normal]
family = "Sarasa Term J"

[font.bold_italic]
style = "Bold"

[font.italic]
style = "Regular"

[window]
opacity = 0.90
dynamic_title = true
padding = { x = 1, y = 1 }

# [colors]
# transparent_background_colors = true

[cursor.style]
blinking = "On"

[terminal]
shell = "zsh"
